#!/bin/bash

if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

rvm use ruby-2.0.0-p195 || exit 100
rvm use ruby-2.0.0-p195@build --create || exit 100
rvm --force gemset empty ruby-2.0.0p195@build || exit 100

case $1 in
patch)
    ;;
install_deps)
    ;;
configure)
    rm Gemfile.lock
    bundle install --quiet
    ;;
compile)
    ;;
check)
    bundle exec rake ci
    ;;
package)
    ;;
upload)
    ;;
compile_extra)
    ;;
uninstall_deps)
    ;;
esac
