#!/bin/bash

if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

branch=$(echo $GIT_BRANCH | cut -d / -f 2)

rvm use ruby-2.7.4 || exit 100
rvm use ruby-2.7.4@$branch --create || exit 100
rvm --force gemset empty ruby-2.7.4@$branch || exit 100

case $1 in
patch)
    ;;
install_deps)
    ;;
configure)
    rm -f Gemfile.lock
    bundle install --quiet
    bundle exec rake app:db:migrate
    bundle exec rake app:db:test:prepare
    ;;
compile)
    ;;
check)
    bundle install --quiet
    bundle exec rake rspec --backtrace
    ;;
package)
    ;;
upload)
    ;;
compile_extra)
    ;;
uninstall_deps)
    ;;
esac
